db:
  db_name: "user-service"
  user: "dev"
  password: "dev"
  host: "db"
  port: 5432
  telegram_user_table_name: "telegram_user"

kafka:
  broker: "kafka:9092"
  telegram_notification_topic: "telegram_notification"
  consumer_group: "telegram_notifier"

telegram:
  bot_token: "<INSERT YOUR TOKEN>"